web: bundle exec unicorn -p $PORT -c ./config/unicorn.rb
worker: bundle exec rake battlecode_arena_batch

config_vars:
  PATH: /app/vendor/bin:/app/local/bin:/app/vendor/nginx/sbin:/app/vendor/php/bin:/app/vendor/php/sbin:/usr/local/bin:/usr/bin:/bin